[tool.poetry]
name = "open-ai-testing"
version = "0.1.0"
description = ""
authors = ["Hannah Smith <hasmith@redhat.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
openai = "^1.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
